language: swift
cache: bundler
os: osx
osx_image: xcode9.4
# before_script:
#- gem install xcpretty
script:
  # Install Brew
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  # Install Vapor
  - brew install vapor/tap/vapor
  # Build App
  - swift build
